##springboot的多环境配置：可以选择激活哪一个配置文件
##spring:
##  profiles:
##    active: dev
##
##server:
##  port: 8080

#server:
#  port: 8081
#spring:
#  profiles:
#    active: dev
#
#---
#
#server:
#  port: 8082
#spring:
#  profiles: dev
#
#---
#
#server:
#  port: 8083
#spring:
#  profiles: test
#



#配置文件到底能写什么？

person:
  name: kzj
  age: 18
  happy: true
  birth: 2020/1/31
  maps: {k1: v1, k2: v2}
  lists:
    - sing
    - dance
    - rap
    - basketball
  dog:
    name: 旺财
    age: 3